### ISSUE TITLE
Use CKEditor

### ISSUE THREAD

**Issue by raeldc** [joomlatools/joomlatools-framework-comments#3]
Use https://github.com/nooku/nooku-ckeditor "basic" template.

**Comment by johanjanssens** [comment]
Note : the editor component is something I did but hasn't been tested. At the same time the code might require additional work, or further improvements for the editor itself.

**Comment by johanjanssens** [comment]
@jebbdomingo Quick note on branch naming, try to use very simple branch names like in this case 3-ckeditor. That is more the clear.

**Comment by raeldc** [comment]
Issue Found: 

![screen shot 2015-11-27 at 3 20 23 pm](https://cloud.githubusercontent.com/assets/66454/11435928/6e63e4ee-951a-11e5-8a2c-ccc960142cd4.png)

The HTML isn't rendered.

**Comment by jebbdomingo** [comment]
@raeldc do we have a countermeasure against xss in place like e.g. htmlpurifier?

**Comment by raeldc** [comment]
@jebbdomingo, by practice, the filter is applied during write operations. So we have a default set of filters that can be used if you check here: 

https://github.com/nooku/nooku-framework/tree/master/code/libraries/koowa/libraries/filter

You can set the filters that you want to use by configuring your table object. Something you're already doing here: https://github.com/nooku/nooku-support/blob/feature/3-ckeditor/administrator/components/com_support/database/table/tickets.php

If you study the HTML filter, you'll see that it already protects you from XSS.

**Comment by jebbdomingo** [comment]
Alright then, we assume it's safe to display user-input html
